#!/bin/bash

EXTENSION_ID=$1
VERSION=( `/usr/bin/flatpak run \
	--branch=stable \
	--arch=x86_64 \
	--command=/app/bin/chromium \
	com.github.Eloston.UngoogledChromium \
	--version` )
VERSION=${VERSION[1]}
FILE="$EXTENSION_ID-$VERSION.crx"
EXT=~/.local/chromium/extensions

if ! [[ $EXTENSION == *.crx ]]; then
	mkdir -p $EXT && cd $EXT
	wget -O $FILE \
	"https://clients2.google.com/service/update2/crx?response=redirect&acceptformat=crx2,crx3&prodversion=$VERSION&x=id%3D$EXTENSION_ID%26installsource%3Dondemand%26uc"
fi

/usr/bin/flatpak run \
	--branch=stable \
	--arch=x86_64 \
	--command=/app/bin/chromium \
	com.github.Eloston.UngoogledChromium \
	$EXT/$FILE
