#!/bin/bash

curl -sL https://deb.nodesource.com/setup_${1:-15}.x | sudo bash -
sudo apt -y install nodejs build-essential gcc g++ make
echo "****************************************"
node -v
echo "DONE!"
