#!/bin/bash

sudo add-apt-repository ppa:linuxuprising/java -y
sudo apt update
sudo apt install oracle-java15-installer -y
sudo apt install oracle-java15-set-default -y

# or

sudo apt install default-jdk
