#!/bin/bash

SUPPORTED="groovy focal bionic xenial"
PLATFORM=$(lsb_release -cs)

if [[ $SUPPORTED =~ *$PLATFORM* ]]; then
	echo "Unfortunately, $PLATFORM is not supported by Docker."
	exit 1;
fi

echo "Installing Docker for $PLATFORM..."

sudo apt install -y \
	apt-transport-https \
	ca-certificates \
	curl \
	gnupg-agent \
	software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88
sudo add-apt-repository -y \
	"deb [arch=amd64] https://download.docker.com/linux/ubuntu \
	$PLATFORM \
	stable"

sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io

sudo systemctl enable docker.service
sudo systemctl enable containerd.service

# Once docker is installed, let's change the user...
echo "Adding $USER to docker group..."
sudo groupadd docker
sudo usermod -aG docker $USER
newgrp docker

echo "Testing docker..."
docker run hello-world
