#!/bin/bash

CMD=$1
shift

if [[ $CMD == "" ]]; then
	if ! [ -e node_modules/ ]; then
		echo "No packages installed, buddo."
	else
		ls node_modules/
	fi
	exit;
fi

function add {
	npm add $@
}

function pull {
	if [ -e package-lock.json ]; then
		rm package-lock.json
	fi
	if [ -e node_modules/$1 ]; then
		rm -rf node_modules/$1
	fi
	npm i $1
}

$CMD $@
