#!/bin/bash

function fetch {
	echo "----------------------------------------"
	echo $(pwd)
	echo
	echo "Pulling from git repository..."
	output=`git pull`
	echo $output
	if ! [[ $output == "Already up-to-date." ]]; then
		echo "Updating node modules..."
		pkgs pull
	fi
}

if ! [ -e $(pwd)/.git ]; then
	for dir in $(ls .); do
		if [ -e $dir/.git ]; then
			cd $dir && fetch && cd ..
		fi
	done
else
	fetch
fi
