#!/bin/bash

function fetch {
	echo "----------------------------------------"
	echo $(pwd)
	echo
	echo "Pulling from git repository..."
	git pull
	echo "Updating node modules..."
	#npm i
	pkgs pull
}

if ! [ -e $(pwd)/.git ]; then
	for dir in $(ls .); do
		if [ -e $dir/.git ]; then
			cd $dir && fetch && cd ..
		fi
	done
else
	fetch
fi
